### ISSUE TITLE
Only ask for elevated access when needed

### ISSUE THREAD

**Issue by leograba** [hiagofranco/tdx-info#14]
This is a proposal.

As of now, the script exits immediately when it is not run as administrator. For many pieces of information, this is not required at all.

The idea is to:

- Identify which options require elevated access
- Ask for elevated access inside the script (needs research for best practices on how to do it)

This would allow things as reduced defaults (https://github.com/hiagofranco/Brict-ToradexInformationTool/issues/13) to be run without asking for `sudo`.

**Comment by hiagofranco** [comment]
Move to Toradex repo: https://github.com/toradex/tdx-info
